# -*- coding: utf-8 -*-
"""Untitled8.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1VVosAkGx-LONnzd0YB9_wZMQYu8uRKuP
"""

from functools import reduce

def calcular_media(datos):
    return reduce(lambda acc, x: acc + x, datos, 0) / len(datos)

def calcular_varianza(datos):
    media = calcular_media(datos)
    return reduce(lambda acc, x: acc + (x - media) ** 2, datos, 0) / len(datos)

# Datos de muestra: calificaciones de estudiantes
calificaciones = [3.5, 4.0, 2.8, 3.9, 4.5, 3.2, 4.8]

# Cálculo de estadísticas
media_calificaciones = calcular_media(calificaciones)
varianza_calificaciones = calcular_varianza(calificaciones)

print(f"Media de calificaciones: {media_calificaciones}")
print(f"Varianza de calificaciones: {varianza_calificaciones}")